//! Deterministic Rust generation from the EXPRESS frontend's successful compilation.
//!
//! Output depends on ordered inputs, including source names and spans. It uses only
//! `std` and `tessstep-schema`; it never reads files, invokes tools, or evaluates EXPRESS.
#![forbid(unsafe_code)]
use std::{
    collections::BTreeSet,
    fmt::{self, Write},
};
use tessstep_express::*;

#[derive(Clone, Copy, Debug)]
pub struct Limits {
    pub max_output_bytes: usize,
    pub max_work: usize,
}
impl Default for Limits {
    fn default() -> Self {
        Self {
            max_output_bytes: 64 * 1024 * 1024,
            max_work: 5_000_000,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Error {
    InvalidCompilation,
    OutputLimit,
    WorkLimit,
    NestingLimit,
}
impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::InvalidCompilation => {
                "generation requires an unmodified successful EXPRESS compilation"
            }
            Self::OutputLimit => "generated output byte limit exceeded",
            Self::WorkLimit => "generation work limit exceeded",
            Self::NestingLimit => "generation domain nesting exceeds 128",
        })
    }
}
impl std::error::Error for Error {}
struct Output {
    text: String,
    limit: usize,
}
impl Write for Output {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        if s.len() > self.limit.saturating_sub(self.text.len()) {
            return Err(fmt::Error);
        }
        self.text.push_str(s);
        Ok(())
    }
}
macro_rules! emit { ($g:expr, $($arg:tt)*) => { write!($g.out, $($arg)*).map_err(|_| Error::OutputLimit)? }; }
struct Generator<'a> {
    c: &'a Compilation,
    ir: &'a SchemaIr,
    out: Output,
    work: usize,
    helper: usize,
}

/// Produce a standalone module (also usable with `include!`) from a successful,
/// unmodified frontend compilation. Unsupported semantics are retained in metadata.
/// No partially generated source is returned on failure. Logical budgets are not RSS caps.
pub fn generate(c: &Compilation, limits: Limits) -> Result<String, Error> {
    let ir = c.ir.as_ref().ok_or(Error::InvalidCompilation)?;
    if c.diagnostics.iter().any(|d| d.severity == Severity::Error)
        || ir.schemas.len() != c.schemas.len()
    {
        return Err(Error::InvalidCompilation);
    }
    let mut g = Generator {
        c,
        ir,
        out: Output {
            text: String::new(),
            limit: limits.max_output_bytes,
        },
        work: limits.max_work,
        helper: 0,
    };
    for s in &ir.schemas {
        g.identifier(&s.name)?;
    }
    for d in &ir.declarations {
        g.identifier(&d.name)?;
        let ast = g.ast(d)?;
        if ast.name.text != d.name {
            return Err(Error::InvalidCompilation);
        }
    }
    emit!(
        g,
        "// Generated by tessstep-codegen 0.1; do not edit.\n// Unchecked owned bindings; EXPRESS expressions are not evaluated.\n"
    );
    g.metadata()?;
    for (schema_id, schema) in ir.schemas.iter().enumerate() {
        emit!(
            g,
            "#[allow(non_camel_case_types, non_snake_case, unused_imports)]\npub mod schema_{} {{\n",
            schema.name.to_ascii_lowercase()
        );
        // Define each explicit attribute domain once, in its declaring schema.
        // Inherited anonymous enums/SELECTs must retain the same Rust identity.
        for (id, d) in ir
            .declarations
            .iter()
            .enumerate()
            .filter(|(_, d)| d.schema == schema_id)
        {
            if let IrKind::Entity { attributes, .. } = &d.kind {
                for (index, a) in attributes
                    .iter()
                    .enumerate()
                    .filter(|(_, a)| matches!(a.kind, AttributeKind::Explicit))
                {
                    g.tick()?;
                    let ty = g.binding_domain(&a.ty, 0)?;
                    let ty = if a.optional {
                        format!("::std::option::Option<{ty}>")
                    } else {
                        ty
                    };
                    emit!(g, "pub type Attribute{id}_{index} = {ty};\n");
                }
            }
        }
        for (id, d) in ir
            .declarations
            .iter()
            .enumerate()
            .filter(|(_, d)| d.schema == schema_id)
        {
            g.tick()?;
            match &d.kind {
                IrKind::Entity { supertypes, .. } => {
                    emit!(
                        g,
                        "#[derive(Clone, Debug, PartialEq)]\npub struct Entity_{} {{\n",
                        d.name
                    );
                    let mut visited = BTreeSet::new();
                    let mut active = BTreeSet::new();
                    let mut stack = vec![(DeclarationId(id), false)];
                    while let Some((current, finish)) = stack.pop() {
                        g.tick()?;
                        if finish {
                            active.remove(&current);
                            visited.insert(current);
                            let IrKind::Entity { attributes, .. } = &g.decl(current)?.kind else {
                                return Err(Error::InvalidCompilation);
                            };
                            for (index, a) in attributes
                                .iter()
                                .enumerate()
                                .filter(|(_, a)| matches!(a.kind, AttributeKind::Explicit))
                            {
                                g.tick()?;
                                g.identifier(&a.name)?;
                                let schema = &ir.schemas[g.decl(current)?.schema].name;
                                emit!(
                                    g,
                                    "pub attr_{}: super::schema_{}::Attribute{}_{index},\n",
                                    a.name.to_ascii_lowercase(),
                                    schema.to_ascii_lowercase(),
                                    current.0
                                );
                            }
                        } else if !visited.contains(&current) {
                            if !active.insert(current) {
                                return Err(Error::InvalidCompilation);
                            }
                            let IrKind::Entity { supertypes, .. } = &g.decl(current)?.kind else {
                                return Err(Error::InvalidCompilation);
                            };
                            stack.push((current, true));
                            stack.extend(supertypes.iter().rev().map(|p| (*p, false)));
                        }
                    }
                    emit!(
                        g,
                        "}}\nimpl ::tessstep_schema::EntityBinding for Entity_{} {{ const DECLARATION: ::tessstep_schema::DeclarationId = ::tessstep_schema::DeclarationId({id}); }}\n",
                        d.name
                    );
                    for parent in supertypes {
                        let path = g.binding_path(*parent)?;
                        emit!(
                            g,
                            "impl ::tessstep_schema::SubtypeOf<{path}> for Entity_{} {{}}\n",
                            d.name
                        );
                    }
                }
                IrKind::Type(ty) => {
                    let ty = g.binding_domain(ty, 0)?;
                    emit!(
                        g,
                        "#[derive(Clone, Debug, PartialEq)]\npub struct Type_{}(pub {ty});\n",
                        d.name
                    );
                }
                IrKind::Constant(_) | IrKind::Unsupported => {}
            }
        }
        // Imported aliases preserve original declaration identity and nominal Rust type.
        for (name, id) in &schema.symbols {
            g.tick()?;
            g.identifier(name)?;
            let d = g.decl(*id)?;
            if d.schema != schema_id {
                let prefix = match d.kind {
                    IrKind::Entity { .. } => "Entity",
                    IrKind::Type(_) => "Type",
                    _ => continue,
                };
                let path = g.binding_path(*id)?;
                emit!(g, "pub use {path} as {prefix}_{name};\n");
            }
        }
        emit!(g, "}}\n");
    }
    Ok(g.out.text)
}
impl<'a> Generator<'a> {
    fn tick(&mut self) -> Result<(), Error> {
        self.work = self.work.checked_sub(1).ok_or(Error::WorkLimit)?;
        Ok(())
    }
    fn identifier(&mut self, s: &str) -> Result<(), Error> {
        self.work = self.work.checked_sub(s.len()).ok_or(Error::WorkLimit)?;
        if !s.as_bytes().first().is_some_and(u8::is_ascii_uppercase)
            || !s
                .bytes()
                .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == b'_')
        {
            return Err(Error::InvalidCompilation);
        }
        Ok(())
    }
    fn decl(&self, id: DeclarationId) -> Result<&'a IrDeclaration, Error> {
        self.ir
            .declarations
            .get(id.0)
            .ok_or(Error::InvalidCompilation)
    }
    fn ast(&self, d: &IrDeclaration) -> Result<&'a Declaration, Error> {
        self.c
            .schemas
            .get(d.schema)
            .and_then(|s| s.declarations.get(d.ast_declaration))
            .ok_or(Error::InvalidCompilation)
    }
    fn binding_path(&self, id: DeclarationId) -> Result<String, Error> {
        let d = self.decl(id)?;
        let schema = self
            .ir
            .schemas
            .get(d.schema)
            .ok_or(Error::InvalidCompilation)?;
        let prefix = match d.kind {
            IrKind::Entity { .. } => "Entity",
            IrKind::Type(_) => "Type",
            _ => return Err(Error::InvalidCompilation),
        };
        Ok(format!(
            "super::schema_{}::{prefix}_{}",
            schema.name.to_ascii_lowercase(),
            d.name
        ))
    }
    fn binding_domain(&mut self, ty: &IrType, depth: usize) -> Result<String, Error> {
        self.tick()?;
        if depth > 128 {
            return Err(Error::NestingLimit);
        }
        Ok(match ty {
            IrType::Builtin { name, .. } => match name.as_str() {
                "BOOLEAN" => "bool",
                "LOGICAL" => "::tessstep_schema::Logical",
                "INTEGER" => "i64",
                "REAL" | "NUMBER" => "f64",
                "STRING" => "::std::string::String",
                "BINARY" => "::std::vec::Vec<bool>",
                _ => return Err(Error::InvalidCompilation),
            }
            .into(),
            IrType::Named(id) => {
                let path = self.binding_path(*id)?;
                if matches!(self.decl(*id)?.kind, IrKind::Entity { .. }) {
                    format!("::tessstep_schema::EntityRef<{path}>")
                } else {
                    path
                }
            }
            IrType::Aggregate {
                optional, element, ..
            } => {
                let element = self.binding_domain(element, depth + 1)?;
                if *optional {
                    format!("::std::vec::Vec<::std::option::Option<{element}>>")
                } else {
                    format!("::std::vec::Vec<{element}>")
                }
            }
            IrType::Enumeration(names) => {
                let name = format!("Domain{}", self.helper);
                self.helper += 1;
                emit!(
                    self,
                    "#[derive(Clone, Debug, PartialEq, Eq)]\npub enum {name} {{\n"
                );
                for n in names {
                    self.identifier(&n.text)?;
                    emit!(self, "Member_{},\n", n.text);
                }
                emit!(self, "}}\n");
                name
            }
            IrType::Select(ids) => {
                let name = format!("Domain{}", self.helper);
                self.helper += 1;
                emit!(
                    self,
                    "#[derive(Clone, Debug, PartialEq)]\npub enum {name} {{\n"
                );
                for id in ids {
                    self.tick()?;
                    let path = self.binding_path(*id)?;
                    let ty = if matches!(self.decl(*id)?.kind, IrKind::Entity { .. }) {
                        format!("::tessstep_schema::EntityRef<{path}>")
                    } else {
                        path
                    };
                    emit!(self, "Alternative_{}({ty}),\n", id.0);
                }
                emit!(self, "}}\n");
                name
            }
        })
    }
    fn span(&mut self, s: Span) -> Result<(), Error> {
        emit!(
            self,
            "::tessstep_schema::SourceSpan {{ source: {}, start: {}, end: {}, line: {}, column: {} }}",
            s.source,
            s.start,
            s.end,
            s.line,
            s.column
        );
        Ok(())
    }
    fn expression(&mut self, e: &Expression) -> Result<(), Error> {
        self.tick()?;
        emit!(
            self,
            "::tessstep_schema::Expression {{ text: {:?}, span: ",
            e.text
        );
        self.span(e.span)?;
        emit!(self, " }}");
        Ok(())
    }
    fn optional_expression(&mut self, e: &Option<Expression>) -> Result<(), Error> {
        if let Some(e) = e {
            emit!(self, "Some(");
            self.expression(e)?;
            emit!(self, ")");
        } else {
            emit!(self, "None");
        }
        Ok(())
    }
    fn rules(&mut self, rules: &[Rule]) -> Result<(), Error> {
        emit!(self, "&[");
        for r in rules {
            self.tick()?;
            emit!(
                self,
                "::tessstep_schema::Rule {{ label: {:?}, expression: ",
                r.label.as_ref().map(|n| n.text.as_str())
            );
            self.expression(&r.expression)?;
            emit!(self, " }},");
        }
        emit!(self, "]");
        Ok(())
    }
    fn ids(&mut self, ids: &[DeclarationId]) -> Result<(), Error> {
        emit!(self, "&[");
        for id in ids {
            self.tick()?;
            self.decl(*id)?;
            emit!(self, "::tessstep_schema::DeclarationId({}),", id.0);
        }
        emit!(self, "]");
        Ok(())
    }
    fn domain(&mut self, ty: &IrType, depth: usize) -> Result<(), Error> {
        self.tick()?;
        if depth > 128 {
            return Err(Error::NestingLimit);
        }
        emit!(self, "::tessstep_schema::Domain::");
        match ty {
            IrType::Builtin { name, width, fixed } => {
                let kind = match name.as_str() {
                    "BOOLEAN" => "Boolean",
                    "LOGICAL" => "Logical",
                    "INTEGER" => "Integer",
                    "NUMBER" => "Number",
                    "REAL" => "Real",
                    "STRING" => "String",
                    "BINARY" => "Binary",
                    _ => return Err(Error::InvalidCompilation),
                };
                emit!(
                    self,
                    "Builtin {{ kind: ::tessstep_schema::Builtin::{kind}, width: "
                );
                self.optional_expression(width)?;
                emit!(self, ", fixed: {fixed} }}");
            }
            IrType::Named(id) => {
                self.decl(*id)?;
                emit!(self, "Named(::tessstep_schema::DeclarationId({}))", id.0);
            }
            IrType::Enumeration(names) => {
                emit!(self, "Enumeration(&[");
                for n in names {
                    self.tick()?;
                    emit!(self, "{:?},", n.text);
                }
                emit!(self, "])");
            }
            IrType::Select(ids) => {
                emit!(self, "Select(");
                self.ids(ids)?;
                emit!(self, ")");
            }
            IrType::Aggregate {
                kind,
                bounds,
                optional,
                unique,
                element,
            } => {
                emit!(
                    self,
                    "Aggregate {{ kind: ::tessstep_schema::AggregateKind::{kind:?}, bounds: "
                );
                if let Some((lo, hi)) = bounds {
                    emit!(self, "Some((");
                    self.expression(lo)?;
                    emit!(self, ",");
                    self.expression(hi)?;
                    emit!(self, "))");
                } else {
                    emit!(self, "None");
                }
                emit!(self, ", optional: {optional}, unique: {unique}, element: &");
                self.domain(element, depth + 1)?;
                emit!(self, " }}");
            }
        }
        Ok(())
    }
    fn symbols(
        &mut self,
        symbols: &std::collections::BTreeMap<String, DeclarationId>,
    ) -> Result<(), Error> {
        emit!(self, "&[");
        for (name, id) in symbols {
            self.tick()?;
            self.decl(*id)?;
            emit!(
                self,
                "::tessstep_schema::Symbol {{ name: {name:?}, declaration: ::tessstep_schema::DeclarationId({}) }},",
                id.0
            );
        }
        emit!(self, "]");
        Ok(())
    }
    fn metadata(&mut self) -> Result<(), Error> {
        emit!(
            self,
            "pub static SCHEMA_SET: ::tessstep_schema::SchemaSet = ::tessstep_schema::SchemaSet {{\nsources: &["
        );
        for source in &self.c.sources {
            self.tick()?;
            emit!(self, "{source:?},");
        }
        emit!(self, "],\nschemas: &[");
        for s in &self.ir.schemas {
            self.tick()?;
            emit!(
                self,
                "::tessstep_schema::Schema {{ name: {:?}, span: ",
                s.name
            );
            self.span(s.span)?;
            emit!(self, ", dependencies: &{:?}, symbols: ", s.dependencies);
            self.symbols(&s.symbols)?;
            emit!(self, ", exports: ");
            self.symbols(&s.exports)?;
            emit!(self, " }},\n");
        }
        emit!(self, "],\ndeclarations: &[");
        for d in &self.ir.declarations {
            self.tick()?;
            let ast = self.ast(d)?;
            emit!(
                self,
                "::tessstep_schema::Declaration {{ name: {:?}, schema: {}, span: ",
                d.name,
                d.schema
            );
            self.span(d.span)?;
            emit!(self, ", kind: ::tessstep_schema::DeclarationKind::");
            match (&d.kind, &ast.kind) {
                (
                    IrKind::Entity {
                        supertypes,
                        attributes,
                    },
                    DeclarationKind::Entity(e),
                ) => {
                    emit!(
                        self,
                        "Entity {{ abstract_entity: {}, supertype_constraint: ",
                        e.abstract_entity
                    );
                    self.optional_expression(&e.supertype)?;
                    emit!(self, ", supertypes: ");
                    self.ids(supertypes)?;
                    emit!(self, ", attributes: &[");
                    for a in attributes {
                        self.tick()?;
                        emit!(
                            self,
                            "::tessstep_schema::Attribute {{ name: {:?}, span: ",
                            a.name
                        );
                        self.span(a.span)?;
                        emit!(self, ", domain: ");
                        self.domain(&a.ty, 0)?;
                        emit!(
                            self,
                            ", optional: {}, kind: ::tessstep_schema::AttributeKind::",
                            a.optional
                        );
                        match &a.kind {
                            AttributeKind::Explicit => emit!(self, "Explicit"),
                            AttributeKind::Derived(e) => {
                                emit!(self, "Derived(");
                                self.expression(e)?;
                                emit!(self, ")");
                            }
                            AttributeKind::Inverse { entity, attribute } => emit!(
                                self,
                                "Inverse {{ entity: {:?}, attribute: {:?} }}",
                                entity.as_ref().map(|n| n.text.as_str()),
                                attribute.text
                            ),
                        }
                        emit!(self, " }},");
                    }
                    emit!(self, "], unique: ");
                    self.rules(&e.unique)?;
                    emit!(self, ", where_rules: ");
                    self.rules(&e.where_rules)?;
                    emit!(self, " }}");
                }
                (IrKind::Type(ty), DeclarationKind::Type { where_rules, .. }) => {
                    emit!(self, "Type {{ domain: ");
                    self.domain(ty, 0)?;
                    emit!(self, ", where_rules: ");
                    self.rules(where_rules)?;
                    emit!(self, " }}");
                }
                (IrKind::Constant(ty), DeclarationKind::Constant { value, .. }) => {
                    emit!(self, "Constant {{ domain: ");
                    self.domain(ty, 0)?;
                    emit!(self, ", value: ");
                    self.expression(value)?;
                    emit!(self, " }}");
                }
                (IrKind::Unsupported, DeclarationKind::Unsupported { keyword, body }) => {
                    emit!(self, "Unsupported {{ keyword: {keyword:?}, body: ");
                    self.expression(body)?;
                    emit!(self, " }}");
                }
                _ => return Err(Error::InvalidCompilation),
            }
            emit!(self, " }},\n");
        }
        emit!(self, "],\nunsupported: &[");
        for d in &self.c.diagnostics {
            self.tick()?;
            emit!(
                self,
                "::tessstep_schema::UnsupportedDiagnostic {{ code: {:?}, message: {:?}, span: ",
                d.code,
                d.message
            );
            self.span(d.span)?;
            emit!(self, " }},");
        }
        emit!(self, "]\n}};\n");
        Ok(())
    }
}
