[package]
name = "tessstep-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
tessstep-ap242 = { path = "../crates/tessstep-ap242" }
tessstep-schema = { path = "../crates/tessstep-schema" }
tessstep-codegen = { path = "../crates/tessstep-codegen" }
tessstep-express = { path = "../crates/tessstep-express" }
libfuzzer-sys = "0.4"
tessstep-part21 = { path = "../crates/tessstep-part21" }
tessstep-model = { path = "../crates/tessstep-model" }

[[bin]]
name = "part21_parser"
path = "fuzz_targets/part21_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "part21_lexer"
path = "fuzz_targets/part21_lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "entity_database"
path = "fuzz_targets/entity_database.rs"
test = false
doc = false
bench = false

[[bin]]
name = "express_frontend"
path = "fuzz_targets/express_frontend.rs"
test = false
doc = false
bench = false

[[bin]]
name = "schema_codegen"
path = "fuzz_targets/schema_codegen.rs"
test = false
doc = false
bench = false

[[bin]]
name = "schema_decoder"
path = "fuzz_targets/schema_decoder.rs"
test = false
doc = false
bench = false

[[bin]]
name = "product_adapter"
path = "fuzz_targets/product_adapter.rs"
test = false
doc = false
bench = false
