use std::{
    hint::black_box,
    time::{Duration, Instant},
};
use tessstep_codegen::{Limits, generate};
use tessstep_express::{Source, compile};
fn main() {
    let mut input = String::from("SCHEMA bench; TYPE measure=REAL; END_TYPE;\n");
    for i in 0..5000 {
        input.push_str(&format!("ENTITY item_{i}; x,y,z:measure; END_ENTITY;\n"));
    }
    input.push_str("END_SCHEMA;");
    let compilation = compile(
        &[Source {
            name: "bench.exp",
            text: &input,
        }],
        Default::default(),
    );
    let expected = generate(&compilation, Limits::default()).unwrap().len();
    let start = Instant::now();
    let mut iterations = 0;
    while start.elapsed() < Duration::from_secs(2) {
        let source = generate(&compilation, Limits::default()).unwrap();
        assert_eq!(source.len(), expected);
        black_box(source);
        iterations += 1;
    }
    let seconds = start.elapsed().as_secs_f64();
    println!(
        "schema-codegen: {iterations} iterations, {:.2} ms/input, {:.2} generated MiB/s, {} source bytes, {expected} generated bytes, 5001 declarations",
        seconds * 1000.0 / f64::from(iterations),
        expected as f64 * f64::from(iterations) / seconds / 1048576.0,
        input.len()
    );
}
