#!/usr/bin/env python3
"""Verify the reduced import profiles and real-file import stages, without AP claims."""
import argparse
import hashlib
import html
import json
import math
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]
EXPECTED = {
    "box.step": ("accepted", "accepted", "accepted"),
    "tube.step": ("accepted", "accepted", "accepted"),
    "open-shell.step": ("accepted", "rejected", "not_run"),
    "nonplanar.step": ("accepted", "rejected", "not_run"),
    "duplicate-point.step": ("rejected", "not_run", "not_run"),
    "missing-point.step": ("rejected", "not_run", "not_run"),
    "curved.step": ("unsupported", "not_run", "not_run"),
}

PLANAR_EXPECTED = {
    "planar-box.step": ("accepted", "accepted", "accepted"),
    "planar-tube.step": ("accepted", "accepted", "accepted"),
    "planar-off-line.step": ("accepted", "rejected", "not_run"),
    "planar-sense.step": ("accepted", "rejected", "not_run"),
    # `$` in a derived ORIENTED_EDGE slot: tolerated by default, rejected when strict.
    "planar-placeholder.step": ("accepted", "accepted", "accepted"),
    "planar-open-shell.step": ("accepted", "rejected", "not_run"),
    "planar-curved.step": ("unsupported", "not_run", "not_run"),
}

TESSELLATED_EXPECTED = {
    "tessellated-cube.step": ("accepted", "accepted", "not_applicable"),
    "tessellated-shell.step": ("accepted", "accepted", "not_applicable"),
    "tessellated-open-solid.step": ("accepted", "rejected", "not_applicable"),
    "tessellated-edge.step": ("accepted", "accepted", "not_applicable"),
    "tessellated-connected.step": ("accepted", "accepted", "not_applicable"),
    "tessellated-bezier.step": ("unsupported", "not_run", "not_applicable"),
}
MESH_KEYS = ("kind", "faces", "linked_faces", "skipped_degenerate", "vertices", "triangles", "boundary_edges")
EDGE_KEYS = ("edges", "connecting_edges", "vertex_items", "joined_points", "pnmax_deviations")
# Authored annotation occurrences: root -> expected graphics counts.
PRESENTATION_EXPECTED = {
    300: {"geometric_set": 100, "styles": 1, "repositioned_items": 4, "vertices": 12, "polylines": 3,
          "polyline_points": 9, "points": 1, "triangles": 3, "skipped_degenerate": 1, "zero_area_triangles": 1},
    301: {"geometric_set": 140, "styles": 0, "repositioned_items": 1, "vertices": 2, "polylines": 1,
          "polyline_points": 2, "points": 0, "triangles": 0, "skipped_degenerate": 0, "zero_area_triangles": 0},
}
PRESENTATION_KEYS = ("geometric_set", "styles", "repositioned_items", "vertices", "polylines", "polyline_points",
                     "triangles", "skipped_degenerate", "zero_area_triangles", "pnmax_deviations")
# Representation selection over tessellated-selection.step (exact preferred):
# root -> (profile, selection, paired roots).
SELECTION_EXPECTED = {
    1000: ("brep", "selected", [21000]), 11000: ("faceted", "selected", [31000]),
    21000: ("tessellated", "alternative", [1000]), 31000: ("tessellated", "alternative", [11000]),
    40002: ("tessellated", "selected", []),
}

def spindle_zone(a, b, h, outer):
    """Integral over z in [-h, h] of (a ± sqrt(b²-z²))², the spindle zone volume over pi."""
    sign = 1 if outer else -1
    return 2 * ((a * a + b * b) * h - h ** 3 / 3 + sign * 2 * a * (h / 2 * math.sqrt(b * b - h * h) + b * b / 2 * math.asin(h / b)))


# Curved B-rep fixtures (generated by corpus/geometry/brep_fixtures.py), checked at a
# 1e-5 m chord: expected stages, adaptations (inferred outer bounds, inserted seams,
# split edges, recharted spheres) and the closed-form volume with its smallest
# curvature radius, or None.
BREP_EXPECTED = {
    "brep-pcurve-cylinder.step": (("accepted",) * 3, (0, 0, 0, 0, 0, 0, 0, 1), (math.pi * 2000e-9, 0.01)),
    "brep-pcurve-bspline-cube.step": (("accepted",) * 3, (0, 0, 0, 0, 0, 0, 4, 0), (1e-6, math.inf)),
    "brep-cylinder.step": (("accepted",) * 3, (0, 1, 0, 0, 0), (math.pi * 2000e-9, 0.01)),
    "brep-seam-cylinder.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (math.pi * 2000e-9, 0.01)),
    "brep-cone.step": (("accepted",) * 3, (0, 1, 0, 0, 0),
                       (math.pi * 10 / 3 * (100 + 10 * (10 + 10 * math.tan(math.pi / 6)) + (10 + 10 * math.tan(math.pi / 6)) ** 2) * 1e-9, 0.01)),
    "brep-torus.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (2 * math.pi ** 2 * 20 * 25e-9, 0.005)),
    "brep-sphere-zone.step": (("accepted",) * 3, (0, 1, 0, 0, 0), (1056 * math.pi * 1e-9, 0.008)),
    # Spindle zones a=5, b=12 between z=±6: pi * integral of (a ± sqrt(b²-z²))² dz.
    "brep-spindle-apple.step": (("accepted",) * 3, (0, 1, 0, 0, 0), (math.pi * spindle_zone(5, 12, 6, True) * 1e-9, (5 + 108 ** 0.5) * 1e-3)),
    "brep-spindle-lemon.step": (("accepted",) * 3, (0, 1, 0, 0, 0), (math.pi * spindle_zone(5, 12, 6, False) * 1e-9, (108 ** 0.5 - 5) * 1e-3)),
    "brep-washer.step": (("accepted",) * 3, (2, 2, 0, 0, 0), (math.pi * 1500e-9, 0.01)),
    "brep-bspline-cube.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (1e-6, math.inf)),
    "brep-bezier-cube.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (1e-6 + 1600 / 9 * 1e-9, 0.002)),
    "brep-uniform-cube.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (1e-6, math.inf)),
    "brep-parabola-prism.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (2000 / 3 * 1e-9, 0.01)),  # apex radius 2f
    "brep-hyperbola-prism.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (125 * (math.sinh(2) - 2) * 1e-9, 0.005)),  # apex radius b^2/a
    "brep-off-surface.step": (("accepted", "rejected", "not_run"), None, None),
    "brep-misaligned.step": (("accepted",) * 3, (0, 1, 1, 0, 0), (math.pi * 2000e-9, 0.01)),
    "brep-sphere-cap.step": (("accepted",) * 3, (0, 0, 0, 1, 0), (math.pi * 16 * 26 / 3 * 1e-9, 0.008)),
    "brep-hemisphere.step": (("accepted",) * 3, (0, 1, 0, 0, 1), (2 / 3 * math.pi * 1e-6, 0.01)),
    "brep-vertex-loop.step": (("accepted",) * 3, (0, 1, 0, 0, 1), (math.pi / 3 * 1e-6, 0.01)),
    "brep-cone-seam.step": (("accepted",) * 3, (0, 0, 0, 0, 1), (math.pi / 3 * 1e-6, 0.01)),
    "brep-sphere.step": (("accepted",) * 3, (0, 1, 0, 1, 2), (4 / 3 * math.pi * 1e-6, 0.01)),
    "brep-sphere-seam.step": (("accepted",) * 3, (0, 0, 0, 0, 2), (4 / 3 * math.pi * 1e-6, 0.01)),
    "brep-bspline-pole.step": (("accepted",) * 3, (0, 0, 0, 0, 1), (1e-6 / 6, math.inf)),
    "brep-extruded-cylinder.step": (("accepted",) * 3, (0, 1, 0, 0, 0), (math.pi * 2000e-9, 0.01)),
    "brep-extruded-ellipse.step": (("accepted",) * 3, (0, 1, 0, 0, 0), (math.pi * 3000e-9, 0.01)),
    "brep-revolved-cone.step": (("accepted",) * 3, (0, 1, 0, 0, 1), (math.pi / 3 * 1e-6, 0.01)),
    "brep-revolved-sphere.step": (("accepted",) * 3, (0, 0, 0, 0, 2), (4 / 3 * math.pi * 1e-6, 0.01)),
    "brep-revolved-torus.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (2 * math.pi ** 2 * 20 * 25e-9, 0.005)),
    "brep-box-cavity.step": (("accepted",) * 3, (0, 0, 0, 0, 0), (7000e-9, math.inf)),
    "brep-sphere-cavity.step": (("accepted",) * 3, (0, 2, 0, 1, 2),
                                (math.pi * 2000e-9 - 4 / 3 * math.pi * 125e-9, 0.005)),
    "brep-inverted-cavity.step": (("accepted", "accepted", "rejected"), None, None),
    "brep-regular-vertex-loop.step": (("accepted", "unsupported", "not_run"), None, None),
    "brep-ambiguous-outer.step": (("accepted", "rejected", "not_run"), None, None),
}
BREP_CHORD = 1e-5
# Mesh components of accepted solids with BREP_WITH_VOIDS cavities (others have one).
BREP_COMPONENTS = {"brep-box-cavity.step": 2, "brep-sphere-cavity.step": 2}
ADAPTATIONS = ("inferred_outer_bounds", "inserted_seams", "split_edges", "recharted_spheres", "collapsed_edges", "collapsed_faces",
               "supplied_pcurves", "rejected_pcurves")


# Product structure linked with the bundled product profile and placed in a scene:
# status, definition nodes, asset instances, world bounds (mm) and total volume (m3).
ASSEMBLY_EXPECTED = {
    "assembly-nested.step": ("accepted", 7, 4, [0, 0, 0, 100, 60, 30], 2.4e-5),
    "assembly-missing-placement.step": ("rejected", None, None, None, None),
    "assembly-unplaced.step": ("accepted", 1, 1, [0, 0, 0, 10, 20, 30], 6e-6),
    "assembly-inch.step": ("accepted", 3, 2, [0, 0, 0, 254, 1524, 762], 12000 * 0.0254 ** 3),
    "assembly-styled.step": ("accepted", 1, 1, [0, 0, 0, 10, 20, 30], 6e-6),
}
# Surface styles adapted to the scene appearance: asset and face styles, materials, bindings.
STYLE_EXPECTED = {"assembly-styled.step": {"asset_styles": 1, "face_styles": 1, "materials": 2, "bindings": 2,
                                           "no_surface_colour": 1, "layers": 1, "excluded": 0}}


def assemble(binary, path):
    started = time.monotonic()
    p = subprocess.run([str(binary), "--meshes", "AUTOMOTIVE_DESIGN", str(path)],
                       capture_output=True, text=True, timeout=300, cwd=ROOT)
    assert p.returncode in (0, 1), (path, p.returncode, p.stderr)
    result = json.loads(p.stdout)
    assert result["format_version"] == 1 and result["scope"] == "product-structure"
    assert (p.returncode == 0) == (result["status"] == "accepted")
    # The report table lists per-stage columns; the product stage is its own row.
    result.update(profile=result["status"], geometry="—", tessellation="—")
    return {"path": str(path), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "result": result, "diagnostic": p.stderr, "seconds": round(time.monotonic()-started, 4)}


def assembly_matches(r, status, nodes, leaves, bounds_mm, volume, volume_tolerance=1e-9):
    if r["status"] != status:
        return False
    if status != "accepted":
        return True
    measured = [round(x * 1e3, 3) for x in r["world_bounds_m"][0] + r["world_bounds_m"][1]]
    return (r["definition_nodes"] == nodes and r["asset_instances"] == leaves and r["failed_imports"] == 0
            and r["unimported_placed"] == 0 and measured == [float(x) for x in bounds_mm]
            and abs(r["volume_m3"] - volume) <= volume_tolerance * volume)


def expected_adaptations(values):
    """Expectation tuples list the leading counters; later ones default to zero."""
    return tuple(values) + (0,) * (len(ADAPTATIONS) - len(values))


def inspect(binary, path, root_id=1000, unit=0.001, scope="faceted-solid", strict=False, extra=()):
    started = time.monotonic()
    p = subprocess.run([str(binary), str(path), str(root_id), str(unit), *(["--strict"] if strict else []), *extra],
                       capture_output=True, text=True, timeout=120, cwd=ROOT)
    assert p.returncode in (0, 1), (path, p.returncode, p.stderr)
    result = json.loads(p.stdout)
    assert result["format_version"] == 1 and result["scope"] == scope
    assert (p.returncode == 0) == (result["status"] == "accepted")
    return {"path": str(path), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "result": result, "diagnostic": p.stderr, "seconds": round(time.monotonic()-started, 4)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--require-external", action="store_true", help="Require the pinned unmodified exporter cuboid")
    args = parser.parse_args()
    subprocess.run(["cargo", "build", "--locked", "-p", "expressc", "-p", "tessstep-import", "--examples"], cwd=ROOT, check=True)
    subprocess.run(["cargo", "build", "--locked", "-p", "expressc"], cwd=ROOT, check=True)
    meta = json.loads(subprocess.check_output(["cargo", "metadata", "--no-deps", "--format-version=1"], cwd=ROOT))
    target = Path(meta["target_directory"]) / "debug"
    suffix = ".exe" if os.name == "nt" else ""
    generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", "corpus/geometry/faceted.exp"], cwd=ROOT)
    assert generated == (ROOT / "crates/tessstep-import/src/profile.rs").read_bytes(), "Regenerate the faceted profile"
    planar_generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", "corpus/geometry/planar.exp"], cwd=ROOT)
    assert planar_generated == (ROOT / "crates/tessstep-import/src/planar_profile.rs").read_bytes(), "Regenerate the planar profile"
    tessellated_generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", "corpus/geometry/tessellated.exp"], cwd=ROOT)
    assert tessellated_generated == (ROOT / "crates/tessstep-import/src/tessellated_profile.rs").read_bytes(), "Regenerate the tessellated profile"
    for profile in ("brep", "context", "product", "style", "pcurve"):
        generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", f"corpus/geometry/{profile}.exp"], cwd=ROOT)
        assert generated == (ROOT / f"crates/tessstep-import/src/{profile}_profile.rs").read_bytes(), f"Regenerate the {profile} profile"
    with tempfile.TemporaryDirectory() as scratch:
        subprocess.run([sys.executable, str(ROOT / "corpus/geometry/brep_fixtures.py"), "--output", scratch], check=True)
        subprocess.run([sys.executable, str(ROOT / "corpus/geometry/assembly_fixtures.py"), "--output", scratch], check=True)
        for fixture in sorted(Path(scratch).iterdir()):
            assert fixture.read_bytes() == (ROOT / "corpus/geometry" / fixture.name).read_bytes(), f"Regenerate {fixture.name}"
    binary = target / "examples" / ("faceted"+suffix)
    planar_binary = target / "examples" / ("planar"+suffix)
    tessellated_binary = target / "examples" / ("tessellated"+suffix)
    presentation_binary = target / "examples" / ("presentation"+suffix)
    survey_binary = target / "examples" / ("survey"+suffix)
    brep_binary = target / "examples" / ("brep"+suffix)
    assembly_binary = target / "examples" / ("assembly"+suffix)
    cases = []
    for name, expected in ASSEMBLY_EXPECTED.items():
        case = assemble(assembly_binary, ROOT / "corpus/geometry" / name)
        case["expected"] = expected
        styles = STYLE_EXPECTED.get(name, {"materials": 0, "bindings": 0})
        case["passed"] = assembly_matches(case["result"], *expected) and (
            expected[0] != "accepted" or all(case["result"]["styles"][k] == v for k, v in styles.items()))
        cases.append(case)
    for name, expected in {**EXPECTED, **PLANAR_EXPECTED}.items():
        planar = name in PLANAR_EXPECTED
        case = inspect(planar_binary if planar else binary, ROOT / "corpus/geometry" / name,
                       scope="planar-solid" if planar else "faceted-solid")
        r = case["result"]
        actual = tuple(r[k] for k in ("profile", "geometry", "tessellation"))
        case["expected"] = expected
        case["passed"] = actual == expected
        if name in {"box.step", "planar-box.step"}:
            case["passed"] &= (r.get("vertices"),r.get("triangles"),r.get("boundary_edges"),r.get("components")) == (8,12,0,1)
            case["passed"] &= math.isclose(r.get("volume_m3",0),6e-6,rel_tol=1e-12)
        if name in {"tube.step", "planar-tube.step"}:
            case["passed"] &= (r.get("vertices"),r.get("triangles"),r.get("boundary_edges"),r.get("components")) == (16,32,0,1)
            case["passed"] &= math.isclose(r.get("volume_m3",0),3.84e-6,rel_tol=1e-12)
        cases.append(case)
    for name in ("planar-placeholder.step", "planar-box.step"):
        case = inspect(planar_binary, ROOT / "corpus/geometry" / name, scope="planar-solid", strict=True)
        expected = ("rejected", "not_run", "not_run") if name == "planar-placeholder.step" else ("accepted", "accepted", "accepted")
        case["expected"] = {"strict": expected}
        case["passed"] = tuple(case["result"][k] for k in ("profile", "geometry", "tessellation")) == expected
        cases.append(case)
    for name, expected in TESSELLATED_EXPECTED.items():
        case = inspect(tessellated_binary, ROOT / "corpus/geometry" / name, scope="tessellated")
        r = case["result"]
        case["expected"] = expected
        case["passed"] = tuple(r[k] for k in ("profile", "geometry", "tessellation")) == expected
        if name == "tessellated-cube.step":
            case["passed"] &= tuple(r.get(k) for k in MESH_KEYS) == ("solid", 6, 1, 1, 8, 12, 0)
            case["passed"] &= math.isclose(r.get("volume_m3", 0), 6e-6, rel_tol=1e-12)
        if name == "tessellated-shell.step":
            case["passed"] &= tuple(r.get(k) for k in MESH_KEYS) == ("shell", 2, 1, 0, 6, 4, 6)
        if name == "tessellated-edge.step":
            case["passed"] &= tuple(r.get(k) for k in MESH_KEYS + EDGE_KEYS) == ("shell", 1, 0, 0, 4, 2, 4, 1, 0, 2, 0, 0)
        if name == "tessellated-connected.step":
            # Per-face coordinate lists close only through the connecting edges.
            case["passed"] &= tuple(r.get(k) for k in MESH_KEYS + EDGE_KEYS) == ("solid", 6, 0, 0, 8, 12, 0, 13, 12, 8, 24, 0)
            case["passed"] &= math.isclose(r.get("volume_m3", 0), 6e-6, rel_tol=1e-12)
        cases.append(case)
    for root, expected in PRESENTATION_EXPECTED.items():
        case = inspect(presentation_binary, ROOT / "corpus/geometry/presentation.step", root, scope="presentation")
        r = case["result"]
        case["expected"] = expected
        case["passed"] = r["status"] == "accepted" and all(r.get(k) == v for k, v in expected.items())
        cases.append(case)
    selection = subprocess.run([str(survey_binary), str(ROOT / "corpus/geometry/tessellated-selection.step"), "0.001"],
                               capture_output=True, text=True, timeout=120, cwd=ROOT, check=True)
    survey = json.loads(selection.stdout)
    found = {r["id"]: (r["profile"], r["selection"], r["paired_with"]) for r in survey["roots"]}
    cases.append({"path": str(ROOT / "corpus/geometry/tessellated-selection.step"), "expected": {str(k): v for k, v in SELECTION_EXPECTED.items()},
                  "result": {"status": "accepted" if found == SELECTION_EXPECTED else "rejected", "profile": "accepted", "geometry": "accepted", "tessellation": "not_applicable", "roots": survey["roots"]},
                  "diagnostic": selection.stderr, "passed": found == SELECTION_EXPECTED and all(r["status"] == "accepted" for r in survey["roots"])})
    for name, (expected, adaptations, volume) in BREP_EXPECTED.items():
        extra = ["--chord", str(BREP_CHORD)] + (["--degrees"] if name == "brep-cone.step" else [])
        case = inspect(brep_binary, ROOT / "corpus/geometry" / name, scope="brep-solid", extra=extra)
        r = case["result"]
        case["expected"] = {"stages": expected, "adaptations": adaptations, "volume": volume}
        case["passed"] = tuple(r[k] for k in ("profile", "geometry", "tessellation")) == expected
        if adaptations is not None:
            case["passed"] &= tuple(r.get(k) for k in ADAPTATIONS) == expected_adaptations(adaptations)
        if volume is not None:
            exact, radius = volume
            bound = 1e-12 if math.isinf(radius) else 2 * BREP_CHORD / radius
            case["passed"] &= r.get("boundary_edges") == 0 and r.get("components") == BREP_COMPONENTS.get(name, 1)
            case["passed"] &= abs(r.get("volume_m3", 0) - exact) <= bound * exact
        cases.append(case)
    # The curved profile reproduces the planar profile's accepted fixtures.
    for name in ("planar-box.step", "planar-tube.step"):
        case = inspect(brep_binary, ROOT / "corpus/geometry" / name, scope="brep-solid")
        r = case["result"]
        case["expected"] = "same volume as the planar profile"
        volume = 6e-6 if name == "planar-box.step" else 3.84e-6
        case["passed"] = r["status"] == "accepted" and math.isclose(r.get("volume_m3", 0), volume, rel_tol=1e-12)
        cases.append(case)
    # Selected upstream adversarial faceted inputs: no copying, healing or expected
    # success is inferred from their parser baseline. These known malformed inputs
    # must never produce a solid mesh under this profile.
    external = Path(os.environ.get("TESSSTEP_CORPUS", str(Path.home()/"step-corpus")))
    upstream = external / "vendor/dodgy-step-files/step-examples"
    for name, root_id in [("12-3a-shells/Tsh002.stp",180),("12-8-mixed/M054.stp",31),
                          ("12-8-mixed/M055.stp",14),("12-8-mixed/M197.stp",14)]:
        path = upstream / name
        if path.is_file():
            case = inspect(binary,path,root_id)
            case["expected"] = "unsupported or rejected; never a mesh"
            case["passed"] = case["result"]["status"] in {"unsupported","rejected"}
            cases.append(case)
    specification = json.loads((ROOT / "corpus/geometry/external-planar.json").read_text())
    cuboid = external / specification["path"]
    if args.require_external and not cuboid.is_file():
        raise RuntimeError(f"Required exporter fixture unavailable: {cuboid}")
    if cuboid.is_file():
        assert hashlib.sha256(cuboid.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = inspect(planar_binary, cuboid, specification["root"], specification["metres_per_unit"], "planar-solid")
        r = case["result"]
        case["expected"] = specification
        case["passed"] = (r["status"] == "accepted" and r.get("vertices") == specification["vertices"]
            and r.get("triangles") == specification["triangles"] and r.get("boundary_edges") == 0
            and r.get("components") == 1 and math.isclose(r.get("volume_m3",0),specification["volume_m3"],rel_tol=1e-12))
        cases.append(case)
    # Unmodified curved exporter B-reps; hashes pin the reviewed inputs.
    for specification in json.loads((ROOT / "corpus/geometry/external-brep.json").read_text()):
        path = external / specification["path"]
        if args.require_external and not path.is_file():
            raise RuntimeError(f"Required exporter fixture unavailable: {path}")
        if not path.is_file():
            continue
        assert hashlib.sha256(path.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = inspect(brep_binary, path, specification["root"], specification["metres_per_unit"], "brep-solid",
                       extra=["--model-tolerance", str(specification["model_tolerance_m"]), "--chord", str(specification["chord_m"])])
        r = case["result"]
        case["expected"] = specification
        case["passed"] = (r["status"] == "accepted" and r.get("boundary_edges") == 0 and r.get("components") == 1
            and tuple(r.get(k) for k in ADAPTATIONS) == expected_adaptations(specification["adaptations"])
            and abs(r.get("volume_m3", 0) - specification["volume_m3"]) <= specification["volume_tolerance"] * specification["volume_m3"])
        cases.append(case)
    # Unmodified exporter tessellations; hashes pin the reviewed inputs.
    for specification in json.loads((ROOT / "corpus/geometry/external-tessellated.json").read_text()):
        path = external / specification["path"]
        if args.require_external and not path.is_file():
            raise RuntimeError(f"Required exporter fixture unavailable: {path}")
        if not path.is_file():
            continue
        assert hashlib.sha256(path.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = inspect(tessellated_binary, path, specification["root"], specification["metres_per_unit"], "tessellated")
        r = case["result"]
        case["expected"] = specification
        case["passed"] = (r["status"] == "accepted" and tuple(r.get(k) for k in MESH_KEYS) == tuple(specification[k] for k in MESH_KEYS)
            and math.isclose(r.get("volume_m3", 0), specification["volume_m3"], rel_tol=1e-12, abs_tol=1e-18))
        cases.append(case)
    # Unmodified exporter annotations; hashes pin the reviewed inputs.
    for specification in json.loads((ROOT / "corpus/geometry/external-presentation.json").read_text()):
        path = external / specification["path"]
        if args.require_external and not path.is_file():
            raise RuntimeError(f"Required exporter fixture unavailable: {path}")
        if not path.is_file():
            continue
        assert hashlib.sha256(path.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = inspect(presentation_binary, path, specification["root"], specification["metres_per_unit"], "presentation")
        strict = inspect(presentation_binary, path, specification["root"], specification["metres_per_unit"], "presentation", strict=True)
        r = case["result"]
        case["expected"] = specification
        case["passed"] = (r["status"] == "accepted" and all(r.get(k) == specification[k] for k in PRESENTATION_KEYS)
                          and strict["result"]["status"] == specification["strict_status"])
        cases.append(case)
    # Unmodified exporter assemblies; hashes pin the reviewed inputs.
    for specification in json.loads((ROOT / "corpus/geometry/external-assembly.json").read_text()):
        path = external / specification["path"]
        if args.require_external and not path.is_file():
            raise RuntimeError(f"Required exporter fixture unavailable: {path}")
        if not path.is_file():
            continue
        assert hashlib.sha256(path.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = assemble(assembly_binary, path)
        case["expected"] = specification
        case["passed"] = (assembly_matches(case["result"], "accepted", specification["definition_nodes"], specification["asset_instances"],
                                           specification["world_bounds_mm"], specification["volume_m3"], specification["volume_tolerance"])
                          and case["result"]["products"] == specification["products"]
                          and all(case["result"]["styles"][k] == v for k, v in specification["styles"].items()))
        cases.append(case)
    output = ROOT / "reports/geometry"
    output.mkdir(parents=True,exist_ok=True)
    report = {"scope":"selected-root faceted, edge-based planar, curved B-rep, existing-tessellation and presentation-tessellation import; no full-document/AP validation",
              "binary_sha256":hashlib.sha256(binary.read_bytes()).hexdigest(),
              "planar_binary_sha256":hashlib.sha256(planar_binary.read_bytes()).hexdigest(),
              "tessellated_binary_sha256":hashlib.sha256(tessellated_binary.read_bytes()).hexdigest(),
              "presentation_binary_sha256":hashlib.sha256(presentation_binary.read_bytes()).hexdigest(),
              "brep_binary_sha256":hashlib.sha256(brep_binary.read_bytes()).hexdigest(),
              "external_available":external.is_dir(),"cases":cases}
    (output/"latest.json").write_text(json.dumps(report,indent=2)+"\n",encoding="utf-8")
    rows=[]
    for c in cases:
        r=c["result"]
        rows.append("<tr>"+"".join("<td>"+html.escape(str(v))+"</td>" for v in
                    [Path(c["path"]).name+(" (strict)" if isinstance(c["expected"],dict) and "strict" in c["expected"] else ""),c["passed"],r["profile"],r["geometry"],r["tessellation"],c["diagnostic"]])+"</tr>")
    (output/"index.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><title>STEP import verification</title>'
        '<style>body{font:16px system-ui;margin:32px}td,th{padding:12px;border:1px solid #ccc;text-align:left}table{border-collapse:collapse}</style>'
        '<h1>STEP import verification</h1><p>Selected-root reduced profiles. Explicit source units. Full AP schema and product validation are unmeasured.</p>'
        '<table><thead><tr><th>File</th><th>Expectation passed</th><th>Profile</th><th>Geometry/topology</th><th>Tessellation</th><th>Diagnostic</th></tr></thead><tbody>'
        +''.join(rows)+'</tbody></table></html>',encoding="utf-8")
    assert all(c["passed"] for c in cases), json.dumps(report,indent=2)
    print(f"planar/faceted/curved/tessellated/presentation import and assembly linking: {len(cases)} reviewed outcomes passed; {output/'index.html'}")


if __name__ == "__main__":
    main()
