#!/usr/bin/env python3
"""Verify the AP242 geometry coverage matrix against the compiled schema.

Every instantiable subtype of GEOMETRIC_REPRESENTATION_ITEM,
TOPOLOGICAL_REPRESENTATION_ITEM and SHAPE_REPRESENTATION in the pinned AP242 long
form must have a recorded status in docs/coverage.json: `adapted` entities are
exactly those declared by an import profile schema in corpus/geometry, and every
other entity is either a named `unsupported` rejection or a recorded `out_of_scope`
decision. docs/COVERAGE.md is generated from the same data.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
ROOTS = ("GEOMETRIC_REPRESENTATION_ITEM", "TOPOLOGICAL_REPRESENTATION_ITEM", "SHAPE_REPRESENTATION")
STATUSES = ("adapted", "supertype", "product", "unsupported", "out_of_scope")


def compiled_entities(expressc, schema):
    output = subprocess.run([str(expressc), "--json", "--max-tokens", "4000000", "--max-work", "100000000", str(schema)],
                            capture_output=True, check=True).stdout
    payload = json.loads(output)
    if not payload["structural_valid"]:
        raise SystemExit("AP242 long form did not compile structurally")
    entities = {d["id"]: d for d in payload["declarations"] if d["kind"] == "entity"}
    children = {}
    for d in entities.values():
        for parent in d["supertypes"]:
            children.setdefault(parent, []).append(d["id"])
    by_name = {d["name"]: d["id"] for d in entities.values()}
    closure = {}
    for root in ROOTS:
        stack = [by_name[root]]
        seen = set()
        while stack:
            current = stack.pop()
            if current in seen:
                continue
            seen.add(current)
            stack.extend(children.get(current, []))
        for i in seen:
            if not entities[i]["abstract"]:
                closure.setdefault(entities[i]["name"], set()).add(root)
    return closure


def profile_entities():
    names = {}
    for path in sorted((ROOT / "corpus/geometry").glob("*.exp")):
        for match in re.finditer(r"(?im)^\s*ENTITY\s+([a-z_0-9]+)", path.read_text(encoding="utf-8")):
            names.setdefault(match.group(1).upper(), []).append(path.stem)
    return names


def classify(closure, coverage, profiles):
    rows = {}
    problems = []
    explicit = coverage["entities"]
    for name in sorted(closure):
        entry = explicit.get(name)
        if entry is None:
            for rule in coverage["rules"]:
                if re.fullmatch(rule["pattern"], name):
                    entry = {"status": rule["status"], "note": rule["reason"], "rule": rule["pattern"]}
                    break
        if entry is None:
            problems.append(f"{name}: no status recorded")
            continue
        if entry["status"] not in STATUSES:
            problems.append(f"{name}: invalid status {entry['status']}")
        if entry["status"] in ("adapted", "supertype") and name not in profiles:
            problems.append(f"{name}: recorded as {entry['status']} but no import profile declares it")
        # The product linker declares representation containers without adapting their items.
        linking = entry["status"] == "product" and set(profiles.get(name, [])) <= {"product"}
        if entry["status"] not in ("adapted", "supertype") and name in profiles and not linking:
            problems.append(f"{name}: declared by profile {profiles[name]} but recorded as {entry['status']}")
        rows[name] = {"status": entry["status"], "note": entry.get("note", ""), "profiles": profiles.get(name, []), "roots": sorted(closure[name])}
    for name in explicit:
        if name not in closure:
            problems.append(f"{name}: explicit entry is not an instantiable AP242 geometry/topology/shape entity")
    return rows, problems


def markdown(rows, coverage, schema_sha):
    counts = {status: sum(r["status"] == status for r in rows.values()) for status in STATUSES}
    lines = ["# AP242 geometry coverage", "",
             "<!-- Generated by scripts/check_coverage.py; edit docs/coverage.json. -->", "",
             f"Every instantiable subtype of `{'`, `'.join(ROOTS)}` in the pinned AP242 MIM long form "
             f"(SHA-256 `{schema_sha[:16]}…`), classified as: **adapted** (declared by an import profile and "
             "covered by `scripts/check_geometry.py`), **supertype** (declared by a profile only as a "
             "supertype; a direct instance is rejected as outside the profile), **product** (evaluated by the product adapter as a placement, not as geometry), **unsupported** (a named, typed "
             "rejection: the import names the entity as outside the selected profile) or **out_of_scope** (a "
             "recorded decision). Structural schema validation of these entities is separate; see "
             "[corpus-testing.md](corpus-testing.md#ap-schema-stage-milestone-21).", "",
             "| Status | Entities |", "| --- | ---: |"]
    lines += [f"| {status} | {counts[status]} |" for status in STATUSES]
    lines += ["", "| Entity | Status | Roots | Profiles | Note |", "| --- | --- | --- | --- | --- |"]
    short = {"GEOMETRIC_REPRESENTATION_ITEM": "geometric", "TOPOLOGICAL_REPRESENTATION_ITEM": "topological", "SHAPE_REPRESENTATION": "shape"}
    for name, row in rows.items():
        lines.append(f"| `{name}` | {row['status']} | {', '.join(short[r] for r in row['roots'])} | {', '.join(row['profiles'])} | {row['note']} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schemas", type=Path, default=Path(os.environ.get("TESSSTEP_SCHEMAS", "~/step-schemas")), help="Directory populated by fetch_schemas.py")
    parser.add_argument("--write", action="store_true", help="Rewrite docs/COVERAGE.md instead of checking it")
    args = parser.parse_args()
    sources = json.loads((ROOT / "corpus/ap-schemas.json").read_text(encoding="utf-8"))
    pinned = next(s for s in sources["schemas"] if s["schema"].startswith("AP242"))
    schema = args.schemas.expanduser().resolve() / pinned["file"]
    if not schema.is_file():
        print(f"{schema} is missing; run scripts/fetch_schemas.py", file=sys.stderr)
        return 2
    if hashlib.sha256(schema.read_bytes()).hexdigest() != pinned["sha256"]:
        print(f"{schema} does not match its pinned SHA-256", file=sys.stderr)
        return 2
    subprocess.run(["cargo", "build", "--locked", "-p", "expressc"], cwd=ROOT, check=True)
    metadata = json.loads(subprocess.check_output(["cargo", "metadata", "--no-deps", "--format-version=1"], cwd=ROOT))
    expressc = Path(metadata["target_directory"]) / "debug" / ("expressc.exe" if os.name == "nt" else "expressc")
    coverage = json.loads((ROOT / "docs/coverage.json").read_text(encoding="utf-8"))
    closure = compiled_entities(expressc, schema)
    rows, problems = classify(closure, coverage, profile_entities())
    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        print(f"{len(problems)} coverage problems", file=sys.stderr)
        return 1
    text = markdown(rows, coverage, pinned["sha256"])
    target = ROOT / "docs/COVERAGE.md"
    if args.write:
        target.write_text(text, encoding="utf-8")
    elif target.read_text(encoding="utf-8") != text:
        print("docs/COVERAGE.md is stale; run scripts/check_coverage.py --write", file=sys.stderr)
        return 1
    counts = {status: sum(r["status"] == status for r in rows.values()) for status in STATUSES}
    print(f"AP242 coverage: {len(rows)} entities; {counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
