#!/usr/bin/env python3
"""Verify the reduced import profiles and real-file import stages, without AP claims."""
import argparse
import hashlib
import html
import json
import math
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]
EXPECTED = {
    "box.step": ("accepted", "accepted", "accepted"),
    "tube.step": ("accepted", "accepted", "accepted"),
    "open-shell.step": ("accepted", "rejected", "not_run"),
    "nonplanar.step": ("accepted", "rejected", "not_run"),
    "duplicate-point.step": ("rejected", "not_run", "not_run"),
    "missing-point.step": ("rejected", "not_run", "not_run"),
    "curved.step": ("unsupported", "not_run", "not_run"),
}

PLANAR_EXPECTED = {
    "planar-box.step": ("accepted", "accepted", "accepted"),
    "planar-tube.step": ("accepted", "accepted", "accepted"),
    "planar-off-line.step": ("accepted", "rejected", "not_run"),
    "planar-sense.step": ("accepted", "rejected", "not_run"),
    # `$` in a derived ORIENTED_EDGE slot: tolerated by default, rejected when strict.
    "planar-placeholder.step": ("accepted", "accepted", "accepted"),
    "planar-open-shell.step": ("accepted", "rejected", "not_run"),
    "planar-curved.step": ("unsupported", "not_run", "not_run"),
}

TESSELLATED_EXPECTED = {
    "tessellated-cube.step": ("accepted", "accepted", "not_applicable"),
    "tessellated-shell.step": ("accepted", "accepted", "not_applicable"),
    "tessellated-open-solid.step": ("accepted", "rejected", "not_applicable"),
    "tessellated-edge.step": ("unsupported", "not_run", "not_applicable"),
}
MESH_KEYS = ("kind", "faces", "linked_faces", "skipped_degenerate", "vertices", "triangles", "boundary_edges")

# Curved B-rep fixtures (generated by corpus/geometry/brep_fixtures.py), checked at a
# 1e-5 m chord: expected stages, adaptations (inferred outer bounds, inserted seams)
# and the closed-form volume with its smallest curvature radius, or None.
BREP_EXPECTED = {
    "brep-cylinder.step": (("accepted",) * 3, (0, 1), (math.pi * 2000e-9, 0.01)),
    "brep-seam-cylinder.step": (("accepted",) * 3, (0, 0), (math.pi * 2000e-9, 0.01)),
    "brep-cone.step": (("accepted",) * 3, (0, 1),
                       (math.pi * 10 / 3 * (100 + 10 * (10 + 10 * math.tan(math.pi / 6)) + (10 + 10 * math.tan(math.pi / 6)) ** 2) * 1e-9, 0.01)),
    "brep-torus.step": (("accepted",) * 3, (0, 0), (2 * math.pi ** 2 * 20 * 25e-9, 0.005)),
    "brep-sphere-zone.step": (("accepted",) * 3, (0, 1), (1056 * math.pi * 1e-9, 0.008)),
    "brep-washer.step": (("accepted",) * 3, (2, 2), (math.pi * 1500e-9, 0.01)),
    "brep-bspline-cube.step": (("accepted",) * 3, (0, 0), (1e-6, math.inf)),
    "brep-off-surface.step": (("accepted", "rejected", "not_run"), None, None),
    "brep-misaligned.step": (("accepted", "unsupported", "not_run"), None, None),
    "brep-vertex-loop.step": (("accepted", "unsupported", "not_run"), None, None),
    "brep-ambiguous-outer.step": (("accepted", "rejected", "not_run"), None, None),
}
BREP_CHORD = 1e-5


def inspect(binary, path, root_id=1000, unit=0.001, scope="faceted-solid", strict=False, extra=()):
    started = time.monotonic()
    p = subprocess.run([str(binary), str(path), str(root_id), str(unit), *(["--strict"] if strict else []), *extra],
                       capture_output=True, text=True, timeout=120, cwd=ROOT)
    assert p.returncode in (0, 1), (path, p.returncode, p.stderr)
    result = json.loads(p.stdout)
    assert result["format_version"] == 1 and result["scope"] == scope
    assert (p.returncode == 0) == (result["status"] == "accepted")
    return {"path": str(path), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "result": result, "diagnostic": p.stderr, "seconds": round(time.monotonic()-started, 4)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--require-external", action="store_true", help="Require the pinned unmodified exporter cuboid")
    args = parser.parse_args()
    subprocess.run(["cargo", "build", "--locked", "-p", "expressc", "-p", "tessstep-import", "--examples"], cwd=ROOT, check=True)
    subprocess.run(["cargo", "build", "--locked", "-p", "expressc"], cwd=ROOT, check=True)
    meta = json.loads(subprocess.check_output(["cargo", "metadata", "--no-deps", "--format-version=1"], cwd=ROOT))
    target = Path(meta["target_directory"]) / "debug"
    suffix = ".exe" if os.name == "nt" else ""
    generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", "corpus/geometry/faceted.exp"], cwd=ROOT)
    assert generated == (ROOT / "crates/tessstep-import/src/profile.rs").read_bytes(), "Regenerate the faceted profile"
    planar_generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", "corpus/geometry/planar.exp"], cwd=ROOT)
    assert planar_generated == (ROOT / "crates/tessstep-import/src/planar_profile.rs").read_bytes(), "Regenerate the planar profile"
    tessellated_generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", "corpus/geometry/tessellated.exp"], cwd=ROOT)
    assert tessellated_generated == (ROOT / "crates/tessstep-import/src/tessellated_profile.rs").read_bytes(), "Regenerate the tessellated profile"
    for profile in ("brep", "context"):
        generated = subprocess.check_output([str(target / ("expressc"+suffix)), "--rust", f"corpus/geometry/{profile}.exp"], cwd=ROOT)
        assert generated == (ROOT / f"crates/tessstep-import/src/{profile}_profile.rs").read_bytes(), f"Regenerate the {profile} profile"
    with tempfile.TemporaryDirectory() as scratch:
        subprocess.run([sys.executable, str(ROOT / "corpus/geometry/brep_fixtures.py"), "--output", scratch], check=True)
        for fixture in sorted(Path(scratch).iterdir()):
            assert fixture.read_bytes() == (ROOT / "corpus/geometry" / fixture.name).read_bytes(), f"Regenerate {fixture.name}"
    binary = target / "examples" / ("faceted"+suffix)
    planar_binary = target / "examples" / ("planar"+suffix)
    tessellated_binary = target / "examples" / ("tessellated"+suffix)
    brep_binary = target / "examples" / ("brep"+suffix)
    cases = []
    for name, expected in {**EXPECTED, **PLANAR_EXPECTED}.items():
        planar = name in PLANAR_EXPECTED
        case = inspect(planar_binary if planar else binary, ROOT / "corpus/geometry" / name,
                       scope="planar-solid" if planar else "faceted-solid")
        r = case["result"]
        actual = tuple(r[k] for k in ("profile", "geometry", "tessellation"))
        case["expected"] = expected
        case["passed"] = actual == expected
        if name in {"box.step", "planar-box.step"}:
            case["passed"] &= (r.get("vertices"),r.get("triangles"),r.get("boundary_edges"),r.get("components")) == (8,12,0,1)
            case["passed"] &= math.isclose(r.get("volume_m3",0),6e-6,rel_tol=1e-12)
        if name in {"tube.step", "planar-tube.step"}:
            case["passed"] &= (r.get("vertices"),r.get("triangles"),r.get("boundary_edges"),r.get("components")) == (16,32,0,1)
            case["passed"] &= math.isclose(r.get("volume_m3",0),3.84e-6,rel_tol=1e-12)
        cases.append(case)
    for name in ("planar-placeholder.step", "planar-box.step"):
        case = inspect(planar_binary, ROOT / "corpus/geometry" / name, scope="planar-solid", strict=True)
        expected = ("rejected", "not_run", "not_run") if name == "planar-placeholder.step" else ("accepted", "accepted", "accepted")
        case["expected"] = {"strict": expected}
        case["passed"] = tuple(case["result"][k] for k in ("profile", "geometry", "tessellation")) == expected
        cases.append(case)
    for name, expected in TESSELLATED_EXPECTED.items():
        case = inspect(tessellated_binary, ROOT / "corpus/geometry" / name, scope="tessellated")
        r = case["result"]
        case["expected"] = expected
        case["passed"] = tuple(r[k] for k in ("profile", "geometry", "tessellation")) == expected
        if name == "tessellated-cube.step":
            case["passed"] &= tuple(r.get(k) for k in MESH_KEYS) == ("solid", 6, 1, 1, 8, 12, 0)
            case["passed"] &= math.isclose(r.get("volume_m3", 0), 6e-6, rel_tol=1e-12)
        if name == "tessellated-shell.step":
            case["passed"] &= tuple(r.get(k) for k in MESH_KEYS) == ("shell", 2, 1, 0, 6, 4, 6)
        cases.append(case)
    for name, (expected, adaptations, volume) in BREP_EXPECTED.items():
        extra = ["--chord", str(BREP_CHORD)] + (["--degrees"] if name == "brep-cone.step" else [])
        case = inspect(brep_binary, ROOT / "corpus/geometry" / name, scope="brep-solid", extra=extra)
        r = case["result"]
        case["expected"] = {"stages": expected, "adaptations": adaptations, "volume": volume}
        case["passed"] = tuple(r[k] for k in ("profile", "geometry", "tessellation")) == expected
        if adaptations is not None:
            case["passed"] &= (r.get("inferred_outer_bounds"), r.get("inserted_seams")) == adaptations
        if volume is not None:
            exact, radius = volume
            bound = 1e-12 if math.isinf(radius) else 2 * BREP_CHORD / radius
            case["passed"] &= r.get("boundary_edges") == 0 and r.get("components") == 1
            case["passed"] &= abs(r.get("volume_m3", 0) - exact) <= bound * exact
        cases.append(case)
    # The curved profile reproduces the planar profile's accepted fixtures.
    for name in ("planar-box.step", "planar-tube.step"):
        case = inspect(brep_binary, ROOT / "corpus/geometry" / name, scope="brep-solid")
        r = case["result"]
        case["expected"] = "same volume as the planar profile"
        volume = 6e-6 if name == "planar-box.step" else 3.84e-6
        case["passed"] = r["status"] == "accepted" and math.isclose(r.get("volume_m3", 0), volume, rel_tol=1e-12)
        cases.append(case)
    # Selected upstream adversarial faceted inputs: no copying, healing or expected
    # success is inferred from their parser baseline. These known malformed inputs
    # must never produce a solid mesh under this profile.
    external = Path(os.environ.get("TESSSTEP_CORPUS", str(Path.home()/"step-corpus")))
    upstream = external / "vendor/dodgy-step-files/step-examples"
    for name, root_id in [("12-3a-shells/Tsh002.stp",180),("12-8-mixed/M054.stp",31),
                          ("12-8-mixed/M055.stp",14),("12-8-mixed/M197.stp",14)]:
        path = upstream / name
        if path.is_file():
            case = inspect(binary,path,root_id)
            case["expected"] = "unsupported or rejected; never a mesh"
            case["passed"] = case["result"]["status"] in {"unsupported","rejected"}
            cases.append(case)
    specification = json.loads((ROOT / "corpus/geometry/external-planar.json").read_text())
    cuboid = external / specification["path"]
    if args.require_external and not cuboid.is_file():
        raise RuntimeError(f"Required exporter fixture unavailable: {cuboid}")
    if cuboid.is_file():
        assert hashlib.sha256(cuboid.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = inspect(planar_binary, cuboid, specification["root"], specification["metres_per_unit"], "planar-solid")
        r = case["result"]
        case["expected"] = specification
        case["passed"] = (r["status"] == "accepted" and r.get("vertices") == specification["vertices"]
            and r.get("triangles") == specification["triangles"] and r.get("boundary_edges") == 0
            and r.get("components") == 1 and math.isclose(r.get("volume_m3",0),specification["volume_m3"],rel_tol=1e-12))
        cases.append(case)
    # Unmodified curved exporter B-reps; hashes pin the reviewed inputs.
    for specification in json.loads((ROOT / "corpus/geometry/external-brep.json").read_text()):
        path = external / specification["path"]
        if args.require_external and not path.is_file():
            raise RuntimeError(f"Required exporter fixture unavailable: {path}")
        if not path.is_file():
            continue
        assert hashlib.sha256(path.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = inspect(brep_binary, path, specification["root"], specification["metres_per_unit"], "brep-solid",
                       extra=["--model-tolerance", str(specification["model_tolerance_m"]), "--chord", str(specification["chord_m"])])
        r = case["result"]
        case["expected"] = specification
        case["passed"] = (r["status"] == "accepted" and r.get("boundary_edges") == 0 and r.get("components") == 1
            and (r.get("inferred_outer_bounds"), r.get("inserted_seams")) == tuple(specification["adaptations"])
            and abs(r.get("volume_m3", 0) - specification["volume_m3"]) <= specification["volume_tolerance"] * specification["volume_m3"])
        cases.append(case)
    # Unmodified exporter tessellations; hashes pin the reviewed inputs.
    for specification in json.loads((ROOT / "corpus/geometry/external-tessellated.json").read_text()):
        path = external / specification["path"]
        if args.require_external and not path.is_file():
            raise RuntimeError(f"Required exporter fixture unavailable: {path}")
        if not path.is_file():
            continue
        assert hashlib.sha256(path.read_bytes()).hexdigest() == specification["sha256"], "Review changed exporter fixture before updating its hash"
        case = inspect(tessellated_binary, path, specification["root"], specification["metres_per_unit"], "tessellated")
        r = case["result"]
        case["expected"] = specification
        case["passed"] = (r["status"] == "accepted" and tuple(r.get(k) for k in MESH_KEYS) == tuple(specification[k] for k in MESH_KEYS)
            and math.isclose(r.get("volume_m3", 0), specification["volume_m3"], rel_tol=1e-12, abs_tol=1e-18))
        cases.append(case)
    output = ROOT / "reports/geometry"
    output.mkdir(parents=True,exist_ok=True)
    report = {"scope":"selected-root faceted, edge-based planar, curved B-rep and existing-tessellation import; no full-document/AP validation",
              "binary_sha256":hashlib.sha256(binary.read_bytes()).hexdigest(),
              "planar_binary_sha256":hashlib.sha256(planar_binary.read_bytes()).hexdigest(),
              "tessellated_binary_sha256":hashlib.sha256(tessellated_binary.read_bytes()).hexdigest(),
              "brep_binary_sha256":hashlib.sha256(brep_binary.read_bytes()).hexdigest(),
              "external_available":external.is_dir(),"cases":cases}
    (output/"latest.json").write_text(json.dumps(report,indent=2)+"\n",encoding="utf-8")
    rows=[]
    for c in cases:
        r=c["result"]
        rows.append("<tr>"+"".join("<td>"+html.escape(str(v))+"</td>" for v in
                    [Path(c["path"]).name+(" (strict)" if isinstance(c["expected"],dict) and "strict" in c["expected"] else ""),c["passed"],r["profile"],r["geometry"],r["tessellation"],c["diagnostic"]])+"</tr>")
    (output/"index.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><title>STEP import verification</title>'
        '<style>body{font:16px system-ui;margin:32px}td,th{padding:12px;border:1px solid #ccc;text-align:left}table{border-collapse:collapse}</style>'
        '<h1>STEP import verification</h1><p>Selected-root reduced profiles. Explicit source units. Full AP schema and product validation are unmeasured.</p>'
        '<table><thead><tr><th>File</th><th>Expectation passed</th><th>Profile</th><th>Geometry/topology</th><th>Tessellation</th><th>Diagnostic</th></tr></thead><tbody>'
        +''.join(rows)+'</tbody></table></html>',encoding="utf-8")
    assert all(c["passed"] for c in cases), json.dumps(report,indent=2)
    print(f"planar/faceted/curved/tessellated import: {len(cases)} reviewed outcomes passed; {output/'index.html'}")


if __name__ == "__main__":
    main()
