#!/usr/bin/env python3
"""Generate a feature table and verify that named test evidence exists."""
import json
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
manifest = json.loads((ROOT / 'docs/conformance.json').read_text(encoding="utf-8"))
tests = '\n'.join(p.read_text(encoding="utf-8") for p in (ROOT / 'crates').glob('*/tests/*.rs'))
lines = ['# Conformance', '', '<!-- Generated by scripts/conformance.py; edit conformance.json. -->', '',
         manifest['scope'] + '.', '',
         'Implemented means the named behavior has regression evidence, not that the full',
         'standard or future semantic layer has been certified. No AP242 support is claimed.', '',
         '| Feature | Status | Test evidence | Limits |', '|---|---|---|---|']
for item in manifest['features']:
    name = item['test']
    if name:
        if name.startswith('tests/capi/'):
            assert name in {'tests/capi/consumer.c', 'tests/capi/consumer.cpp'}
            assert 'int main(' in (ROOT / name).read_text(encoding='utf-8'), f'Missing consumer: {name}'
        else:
            assert f'fn {name}(' in tests, f'Missing test evidence: {name}'
    lines.append(f"| {item['feature']} | {item['status']} | {name or '—'} | {item['limitations']} |")
lines += ['', 'The JSON manifest tracks physical syntax, the EXPRESS frontend and generated bindings.',
          'Initial structural instance decoding is a separate checked stage; full schema',
          'conformance, semantic interpretation and tessellation remain future work.', '',
          'See [PART21.md](PART21.md), [ERROR_MODEL.md](ERROR_MODEL.md) and',
          '[VALIDATION.md](VALIDATION.md) for exact behavior and actual verification results.']
content = '\n'.join(lines) + '\n'
path = ROOT / 'docs/CONFORMANCE.md'
if '--check' in sys.argv:
    assert path.read_text(encoding="utf-8") == content, 'Regenerate docs/CONFORMANCE.md'
    print('conformance: generated table and test evidence passed')
else:
    path.write_text(content, encoding="utf-8")
