[package]
name = "tessstep-ap242"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tessstep-model.workspace = true
tessstep-schema.workspace = true
tessstep-part21.workspace = true
tessstep-product.workspace = true

[lints]
workspace = true

[[bench]]
name = "product"
harness = false
