[package]
name = "tessstep-tessellate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tessstep-trim.workspace = true
tessstep-math.workspace = true
tessstep-curves.workspace = true
tessstep-topology.workspace = true

[lints]
workspace = true

[dev-dependencies]
tessstep-surfaces.workspace = true

[[bench]]
name = "boundaries"
harness = false
