[package]
name = "tessstep"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tessstep-curves.workspace = true
tessstep-math.workspace = true
tessstep-product.workspace = true
tessstep-ap242.workspace = true
tessstep-schema.workspace = true
tessstep-codegen.workspace = true
tessstep-express.workspace = true
tessstep-part21.workspace = true
tessstep-model.workspace = true

[lints]
workspace = true
